//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.17.0
//     from Assets/ClimberControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/ClimberControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @ClimberInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @ClimberInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""ClimberControls"",
    ""maps"": [
        {
            ""name"": ""PlayerLeft"",
            ""id"": ""5c40e2a9-0b3c-4455-9bfa-5468a8c0df37"",
            ""actions"": [
                {
                    ""name"": ""HandMove"",
                    ""type"": ""Value"",
                    ""id"": ""4adf7e48-9776-4dc7-a623-8182b97f1a0b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FootMove"",
                    ""type"": ""Value"",
                    ""id"": ""4c84a081-816d-4338-b8f8-96da32fd90b4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Grip"",
                    ""type"": ""Button"",
                    ""id"": ""5a86cd89-bbcb-41c5-8366-6dab37ed25f0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenShop"",
                    ""type"": ""Button"",
                    ""id"": ""f7635a71-bbbc-4480-9be1-39f4d0106a10"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0f62388a-7a9e-4a81-95dd-4e81c0a3230d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1eeb8d59-c509-44e6-a3d2-48a0ddf1a58f"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FootMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""369f1c42-9dcb-40db-9f54-c69bc90b08f1"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0799ab5-a688-4f75-abd3-a82c53dbe759"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenShop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerRight"",
            ""id"": ""f2a178dd-0997-45d1-b2e0-95c8cf7dfc68"",
            ""actions"": [
                {
                    ""name"": ""HandMove"",
                    ""type"": ""Value"",
                    ""id"": ""81e40ba1-ccf6-45af-b0d8-51f28da74645"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FootMove"",
                    ""type"": ""Button"",
                    ""id"": ""58170aa1-4451-484a-8a5a-e47f9ef5b2f2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Grip"",
                    ""type"": ""Button"",
                    ""id"": ""53fe5b48-76c5-4883-894c-2df5e03ec3b2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b1f5ed45-70cd-4a54-8dbf-8412fe4d399c"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b363106d-fb05-4c81-85ed-68cbabda2dea"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FootMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7d86d68-33cc-4422-874a-4fba1573b6d5"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerLeft
        m_PlayerLeft = asset.FindActionMap("PlayerLeft", throwIfNotFound: true);
        m_PlayerLeft_HandMove = m_PlayerLeft.FindAction("HandMove", throwIfNotFound: true);
        m_PlayerLeft_FootMove = m_PlayerLeft.FindAction("FootMove", throwIfNotFound: true);
        m_PlayerLeft_Grip = m_PlayerLeft.FindAction("Grip", throwIfNotFound: true);
        m_PlayerLeft_OpenShop = m_PlayerLeft.FindAction("OpenShop", throwIfNotFound: true);
        // PlayerRight
        m_PlayerRight = asset.FindActionMap("PlayerRight", throwIfNotFound: true);
        m_PlayerRight_HandMove = m_PlayerRight.FindAction("HandMove", throwIfNotFound: true);
        m_PlayerRight_FootMove = m_PlayerRight.FindAction("FootMove", throwIfNotFound: true);
        m_PlayerRight_Grip = m_PlayerRight.FindAction("Grip", throwIfNotFound: true);
    }

    ~@ClimberInputActions()
    {
        UnityEngine.Debug.Assert(!m_PlayerLeft.enabled, "This will cause a leak and performance issues, ClimberInputActions.PlayerLeft.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerRight.enabled, "This will cause a leak and performance issues, ClimberInputActions.PlayerRight.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerLeft
    private readonly InputActionMap m_PlayerLeft;
    private List<IPlayerLeftActions> m_PlayerLeftActionsCallbackInterfaces = new List<IPlayerLeftActions>();
    private readonly InputAction m_PlayerLeft_HandMove;
    private readonly InputAction m_PlayerLeft_FootMove;
    private readonly InputAction m_PlayerLeft_Grip;
    private readonly InputAction m_PlayerLeft_OpenShop;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerLeft".
    /// </summary>
    public struct PlayerLeftActions
    {
        private @ClimberInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerLeftActions(@ClimberInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerLeft/HandMove".
        /// </summary>
        public InputAction @HandMove => m_Wrapper.m_PlayerLeft_HandMove;
        /// <summary>
        /// Provides access to the underlying input action "PlayerLeft/FootMove".
        /// </summary>
        public InputAction @FootMove => m_Wrapper.m_PlayerLeft_FootMove;
        /// <summary>
        /// Provides access to the underlying input action "PlayerLeft/Grip".
        /// </summary>
        public InputAction @Grip => m_Wrapper.m_PlayerLeft_Grip;
        /// <summary>
        /// Provides access to the underlying input action "PlayerLeft/OpenShop".
        /// </summary>
        public InputAction @OpenShop => m_Wrapper.m_PlayerLeft_OpenShop;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerLeft; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerLeftActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerLeftActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerLeftActions" />
        public void AddCallbacks(IPlayerLeftActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerLeftActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerLeftActionsCallbackInterfaces.Add(instance);
            @HandMove.started += instance.OnHandMove;
            @HandMove.performed += instance.OnHandMove;
            @HandMove.canceled += instance.OnHandMove;
            @FootMove.started += instance.OnFootMove;
            @FootMove.performed += instance.OnFootMove;
            @FootMove.canceled += instance.OnFootMove;
            @Grip.started += instance.OnGrip;
            @Grip.performed += instance.OnGrip;
            @Grip.canceled += instance.OnGrip;
            @OpenShop.started += instance.OnOpenShop;
            @OpenShop.performed += instance.OnOpenShop;
            @OpenShop.canceled += instance.OnOpenShop;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerLeftActions" />
        private void UnregisterCallbacks(IPlayerLeftActions instance)
        {
            @HandMove.started -= instance.OnHandMove;
            @HandMove.performed -= instance.OnHandMove;
            @HandMove.canceled -= instance.OnHandMove;
            @FootMove.started -= instance.OnFootMove;
            @FootMove.performed -= instance.OnFootMove;
            @FootMove.canceled -= instance.OnFootMove;
            @Grip.started -= instance.OnGrip;
            @Grip.performed -= instance.OnGrip;
            @Grip.canceled -= instance.OnGrip;
            @OpenShop.started -= instance.OnOpenShop;
            @OpenShop.performed -= instance.OnOpenShop;
            @OpenShop.canceled -= instance.OnOpenShop;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerLeftActions.UnregisterCallbacks(IPlayerLeftActions)" />.
        /// </summary>
        /// <seealso cref="PlayerLeftActions.UnregisterCallbacks(IPlayerLeftActions)" />
        public void RemoveCallbacks(IPlayerLeftActions instance)
        {
            if (m_Wrapper.m_PlayerLeftActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerLeftActions.AddCallbacks(IPlayerLeftActions)" />
        /// <seealso cref="PlayerLeftActions.RemoveCallbacks(IPlayerLeftActions)" />
        /// <seealso cref="PlayerLeftActions.UnregisterCallbacks(IPlayerLeftActions)" />
        public void SetCallbacks(IPlayerLeftActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerLeftActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerLeftActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerLeftActions" /> instance referencing this action map.
    /// </summary>
    public PlayerLeftActions @PlayerLeft => new PlayerLeftActions(this);

    // PlayerRight
    private readonly InputActionMap m_PlayerRight;
    private List<IPlayerRightActions> m_PlayerRightActionsCallbackInterfaces = new List<IPlayerRightActions>();
    private readonly InputAction m_PlayerRight_HandMove;
    private readonly InputAction m_PlayerRight_FootMove;
    private readonly InputAction m_PlayerRight_Grip;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerRight".
    /// </summary>
    public struct PlayerRightActions
    {
        private @ClimberInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerRightActions(@ClimberInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerRight/HandMove".
        /// </summary>
        public InputAction @HandMove => m_Wrapper.m_PlayerRight_HandMove;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRight/FootMove".
        /// </summary>
        public InputAction @FootMove => m_Wrapper.m_PlayerRight_FootMove;
        /// <summary>
        /// Provides access to the underlying input action "PlayerRight/Grip".
        /// </summary>
        public InputAction @Grip => m_Wrapper.m_PlayerRight_Grip;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerRight; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerRightActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerRightActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerRightActions" />
        public void AddCallbacks(IPlayerRightActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerRightActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerRightActionsCallbackInterfaces.Add(instance);
            @HandMove.started += instance.OnHandMove;
            @HandMove.performed += instance.OnHandMove;
            @HandMove.canceled += instance.OnHandMove;
            @FootMove.started += instance.OnFootMove;
            @FootMove.performed += instance.OnFootMove;
            @FootMove.canceled += instance.OnFootMove;
            @Grip.started += instance.OnGrip;
            @Grip.performed += instance.OnGrip;
            @Grip.canceled += instance.OnGrip;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerRightActions" />
        private void UnregisterCallbacks(IPlayerRightActions instance)
        {
            @HandMove.started -= instance.OnHandMove;
            @HandMove.performed -= instance.OnHandMove;
            @HandMove.canceled -= instance.OnHandMove;
            @FootMove.started -= instance.OnFootMove;
            @FootMove.performed -= instance.OnFootMove;
            @FootMove.canceled -= instance.OnFootMove;
            @Grip.started -= instance.OnGrip;
            @Grip.performed -= instance.OnGrip;
            @Grip.canceled -= instance.OnGrip;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerRightActions.UnregisterCallbacks(IPlayerRightActions)" />.
        /// </summary>
        /// <seealso cref="PlayerRightActions.UnregisterCallbacks(IPlayerRightActions)" />
        public void RemoveCallbacks(IPlayerRightActions instance)
        {
            if (m_Wrapper.m_PlayerRightActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerRightActions.AddCallbacks(IPlayerRightActions)" />
        /// <seealso cref="PlayerRightActions.RemoveCallbacks(IPlayerRightActions)" />
        /// <seealso cref="PlayerRightActions.UnregisterCallbacks(IPlayerRightActions)" />
        public void SetCallbacks(IPlayerRightActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerRightActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerRightActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerRightActions" /> instance referencing this action map.
    /// </summary>
    public PlayerRightActions @PlayerRight => new PlayerRightActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerLeft" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerLeftActions.AddCallbacks(IPlayerLeftActions)" />
    /// <seealso cref="PlayerLeftActions.RemoveCallbacks(IPlayerLeftActions)" />
    public interface IPlayerLeftActions
    {
        /// <summary>
        /// Method invoked when associated input action "HandMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHandMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FootMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFootMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Grip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGrip(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenShop" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenShop(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerRight" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerRightActions.AddCallbacks(IPlayerRightActions)" />
    /// <seealso cref="PlayerRightActions.RemoveCallbacks(IPlayerRightActions)" />
    public interface IPlayerRightActions
    {
        /// <summary>
        /// Method invoked when associated input action "HandMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHandMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FootMove" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFootMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Grip" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGrip(InputAction.CallbackContext context);
    }
}
